export const REORDER_BLOCK = 'REORDER_BLOCK';
export const ADD_BLOCK = 'ADD_BLOCK';
export const SELECT_BLOCK = 'SELECT_BLOCK';
export const UPDATE_BLOCK = 'UPDATE_BLOCK';
export const REMOVE_BLOCK = 'REMOVE_BLOCK';
export const UPDATE_SELECTED_BLOCK = 'UPDATE_SELECTED_BLOCK';